### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by R0GGER** [linuxserver/docker-pydio#1]
After build (with Shipyard) I get this error...

403 Forbidden
nginx/1.4.6 (Ubuntu)

**Comment by sparklyballs** [comment]
sounds like you messed something up with shipyard.

**Comment by R0GGER** [comment]
Helpful answer..

**Comment by sparklyballs** [comment]
more information required...

but you knew that already.

**Comment by pecigonzalo** [comment]
@R0GGER Can you paste your Shipyard configuration or a docker inspect?

**Comment by lonix** [comment]
Closing, Due to lack of respons
