### ISSUE TITLE
New nginx configuration for pydio 7

### ISSUE THREAD

**Issue by Pusnow** [linuxserver/docker-pydio#11]
Current version of nginx configuration is for pydio 6.
Pydio 7's nginx configuration is quite different including rewrite rules and fastcgi_param.
I think it should be updated.
[link](https://pydio.com/en/docs/kb/system/installing-debiannginx)

**Comment by sparklyballs** [comment]
@Pusnow, you're very welcome to submit a pr against the repo

**Comment by j0nnymoe** [comment]
closing ticket as this is being dealt with in a PR #13 .
