### ISSUE TITLE
Cache error ... pydio not working

### ISSUE THREAD

**Issue by Koxx3** [linuxserver/docker-pydio#16]
Hi,
I am running the latest docker and I can't get it working.
It is linked with a mysql db.

Each time I try to create something, I get this message :(

`
date	ip	level	user	action	source	params	cursor	text	ajxp_im_time	

05-05-17 20:41:31	PHP_CLI	ERROR	adminkoxx	error l.353	Controller.php	message=Parameter 1 to Pydio\Gui\RichClient::nodeBookmarkMetadata() expected to be a reference, value given	21	05-05-17 20:41:31	1494017126	
`

**Comment by Koxx3** [comment]
by the way, I use the release from 1 week ago, and everything was working fine !

I got various errors : 
`date	ip	level	user	action	source	params	cursor	text	ajxp_im_time	

05-05-17 21:07:23	172.17.0.1	ERROR	adminkoxx	error l.353 (2)	Controller.php	message=Parameter 1 to Pydio\Cache\Core\CoreCacheLoader::loadNodeInfoFromCache() expected to be a reference, value given	13	05-05-17 21:07:23	1494018459	
`

**Comment by Koxx3** [comment]
I just checked out release 51, and no issue at all !

**Comment by fiws** [comment]
same problem. Seems like this will also lock the sqlite db if using that instead of mysql, which results in all sorts of weird behaviour.

**Comment by sparklyballs** [comment]
updating to pydio8 resolves this issue.
