### ISSUE TITLE
Public link sharing do not work

### ISSUE THREAD

**Issue by jarlave** [linuxserver/docker-pydio#2]
I tried your docker and foudn out that public link sharing do not work, I need to create the public folder by myself in /config/www/pydio/data/ to make it work. Maybe make a mkdir in one of the init scripts for the /config/www/pydio/data/public folder?
Without this folder it doesn't work.

**Comment by G-Ray** [comment]
+1 I confirm

**Comment by sparklyballs** [comment]
we will be hopefully rebasing the base image this docker uses in the near future.
at that time we will address this and the other pydio issues.

#5 , #3

**Comment by Battleroid** [comment]
Same issue, but adding a new directory at `/config/www/pydio/data/public` works fine.

**Comment by ncoder-1** [comment]
Same issue as well.  Tried adding the public directory but didn't work.  This is after a fresh docker create and upgrade to 7.0.3.

**Comment by himiloshpetrov** [comment]
It seems that there's a bug in the file "root/etc/cont-init.d/60-config" -- the arguments of the sed command have extra slashes that should probably be removed.

Because of this bug, Pydio uses "/config/www/pydio/data" instead of "/data", as it's intended to be.

**Comment by sparklyballs** [comment]
@miloshpetrov there isn't a bug in that file
the seds work as they should and pydio is using /data as install base and file storage.
public links need to be configured via the webui it would seem in 

settings -> application core

**Comment by himiloshpetrov** [comment]
@sparklyballs 

1) That's how I check whether sed is not working:
    a) docker run -d --name pydio linuxserver/pydio
    b) docker exec pydio cat /config/www/pydio/conf/bootstrap_context.php | grep AJXP_DATA_PATH
    c) Observe, AJXP_DATA_PATH is not pointing to /data

2) In the code, what's the purpose of a slash in 's#\define' ?

3) That's how I check that files are saved in /config/www/pydio/data, not in /data:
    a) Go through Pydio web setup
    b) In browser, open "Common files", click "Upload", upload any file
    c) docker exec -it pydio ls /data/files/ # empty output
    d) docker exec -it pydio ls /config/www/pydio/data/files/ # file is here

**Comment by sparklyballs** [comment]
`sparklyballs@Docker-DEV:~$ docker run -d --name pydio linuxserver/pydio
Unable to find image 'linuxserver/pydio:latest' locally
latest: Pulling from linuxserver/pydio
2949e2ae3b3c: Already exists
04d3fd2fe93c: Already exists
38420d51fe05: Already exists
97a76d582231: Already exists
192023db52a4: Already exists
5684effac56a: Pull complete
b93ed266bb50: Pull complete
Digest: sha256:2b75043ed0b72dc5d6a916d2abae755c60e0922d2be5cc51ba7b1aad63f3209e
Status: Downloaded newer image for linuxserver/pydio:latest
f2ea09c863104220980aa26e5dc1eb2b2ad1a890cd31299b625dd7752cb10ae3
sparklyballs@Docker-DEV:~$ docker exec pydio cat /config/www/pydio/conf/bootstrap_context.php | grep AJXP_DATA_PATH
cat: /config/www/pydio/conf/bootstrap_context.php: No such file or directory
sparklyballs@Docker-DEV:~$ docker exec pydio cat /config/www/pydio/conf/bootstrap_context.php | grep AJXP_DATA_PATH
define("AJXP_DATA_PATH", AJXP_INSTALL_PATH."/data");
define("AJXP_CACHE_DIR", AJXP_DATA_PATH."/cache");
define("TESTS_RESULT_FILE", AJXP_DATA_PATH."/plugins/boot.conf/diag_result.php");
    }else if(file_exists(AJXP_DATA_PATH."/plugins/boot.conf/encoding.php")){
        require_once(AJXP_DATA_PATH."/plugins/boot.conf/encoding.php");`

**Comment by sparklyballs** [comment]
the first grep the files hadn't finished downloading/unpacking.

**Comment by himiloshpetrov** [comment]
@sparklyballs , in your output the first line is:
`define("AJXP_DATA_PATH", AJXP_INSTALL_PATH."/data");`
This means that the sed command didn't work. If sed worked, the line would have looked like this:
`define("AJXP_DATA_PATH", "/data");`

**Comment by mrsakkaro** [comment]
Is this a persisting issue? I nuked my pydio 7 docker setting to get the fresh pydio 8 installed, but my sharing is not working. I tried adding a directory like everyone else has tried, but still has not worked. Any clue as to what is causing the issue?

**Comment by lucasdiedrich** [comment]
It seems that the problem still persist, not only with sharing but using it with collabora too:

```bash
2017/08/01 14:35:45 [error] 290#290: *369 open() "/config/www/pydio/wopi/files/1/UntitledDocument.docx" failed (2: No such file or directory), client: 172.17.0.1, server: _, request: "GET /wopi/files/1/UntitledDocument.docx?access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbiI6InQ2M3ptbW9kS0hGRlVKTzEzbDZQU3dibCIsImhhc2giOiIyOTI3NjYzNGZmNGNhNDA2MzE4OTEzZjZhNmViZGZhOGViMzMxZmI2Ojc5YTUyNTcyMTQ0NTAxMTdiYzczZTI2OTFlYjQwOGI5Zjc0ZmRiNDQ0NTFkMjYyOTc5YTg4MDY5OWZiNDUzOGUiLCJ1cmkiOiJcL3dvcGlcL2ZpbGVzXC8xXC9VbnRpdGxlZERvY3VtZW50LmRvY3giLCJ0YXNrIjoiZWRpdG9yLmxpYnJlb2ZmaWNlIn0.JfDEW5v6p6Gqer7080gLr9XtVIjWkfAGFOF_W01UzLY&access_token_ttl=0&permission=edit HTTP/1.1", host: "arquivos.domain"
```

Edit: After applying the #13 and changing the nginx default file the collabora started to work.

**Comment by KetchupBomb** [comment]
@lucasdiedrich, did you have to re-build the image, or can you swap out `/defaults/default` from #13 within an existing container and restart it? (I've tried this, and still no luck thus far.)

---

Errors from Pydio logs show when trying to access a shared object:

```
==> /config/log/pydio/access_pydio6_log <==
192.168.123.3 - - [04/Aug/2017:00:02:40 +0000] "GET /public/b48585 HTTP/1.1" 404 200 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
==> /config/log/pydio/error_pydio6_log <==
2017/08/04 00:02:40 [error] 291#291: *301 open() "/config/www/pydio/public/b48585" failed (2: No such file or directory), client: 192.168.123.3, server: _, request: "GET /public/b48585 HTTP/1.1", host: "redacted"
```

**Comment by lucasdiedrich** [comment]
@KetchupBomb , i didn't rebuild the image, the only thing i did i updated the server and changed the file i think.
