### ISSUE TITLE
php-fpm won't run as root

### ISSUE THREAD

**Issue by thehomerepot** [linuxserver/docker-pydio#20]
The output below is from the docker logs pydio output.
[03-Aug-2017 15:33:42] ERROR: [pool www] please specify user and group other than root
[03-Aug-2017 15:33:42] ERROR: FPM initialization failed

This prevents the webpage from loading. I did the following to resolve.

In this file /etc/services.d/php-fpm/run
Replaced this
exec /usr/sbin/php-fpm7 -F

With this
exec /usr/sbin/php-fpm7 -F -R

**Comment by thehomerepot** [comment]
Alternatively you could update the documentation for this docker image to note not to use PUID=0

**Comment by aptalca** [comment]
The documentation states to use the uid of the regular user account. Linux users are highly recommended against running as root. 
We don't support our containers being run as root (some even refuse to work as you found out).

**Comment by thehomerepot** [comment]
I understand the recommendation not to use root, but the documentation isn't clear about it for your docker image. For example.

"Ensure the data volume directory on the host is owned by the same user you specify and it will "just work" ™."

Simply being more explicit would be helpful.
