### ISSUE TITLE
Mail sending is not working ssmtp.conf filled

### ISSUE THREAD

**Issue by Homer-Sim** [linuxserver/docker-pydio#25]
Hello I added my mail configuration to ssmtp.conf and acc to pydio forum I did this within pydio container

`ssmtp -v mymail@yahoo.com < message.txt
[<-] 220 kundenserver.de (mreue105) Nemesis ESMTP Service ready
[->] EHLO 450eaf5d19cb
[<-] 250 STARTTLS
[->] STARTTLS
[<-] 220 OK
[->] EHLO 450eaf5d19cb
[<-] 250 SIZE 69920427
[->] AUTH LOGIN
[<-] 334 VXNlcm5hbWU6
[->] Y2xvdWRAb2lsLXRlYy5kZQ==
[<-] 334 UGFzc3dvcmQ6
[<-] 235 Authentication succeeded
[->] MAIL FROM:<yourmail@gmail.com>
[<-] 250 Requested mail action okay, completed
[->] RCPT TO:<mymail@yahoo.com>
[<-] 250 OK
[->] DATA
[<-] 354 Start mail input; end with <CRLF>.<CRLF>
[->] Received: by 450eaf5d19cb (sSMTP sendmail emulation); Wed, 15 Nov 2017 20:49:45 +0100
[->] Date: Wed, 15 Nov 2017 20:49:45 +0100
[->] To: yourmail@gmail.com
[->] From: yourmail@gmail.com
[->] Subject: Testmessage
[->] This is a test for sending
[->]
[->] .
[<-] 250 Requested mail action okay, completed: id=0LcxWa-1ewxAI0jGC-00iAyL
[->] QUIT
[<-] 221 kundenserver.de Service closing transmission channel
`
it should work. If I am sending a shared folder mail to a mail reciepent I am getting from pydio a mail sent message. No error entry in pydio logs.

Any ideas what could be wrong?

**Comment by homerr** [comment]
Looks as if the container was working alright, and the mail was transported, but it could have been an issue with filtering on the other end killing it off. Closing as container seems fine.
