### ISSUE TITLE
Public link and reverse proxy apache2

### ISSUE THREAD

**Issue by cmalcolmx** [linuxserver/docker-pydio#31]
Hi,
(Debian 8, Apache2, Php7.0, Pydio8)

My pydio server is behind an apache reverse proxy. 
Everything is working except public link. When I wanna share a file thanks to public link, the link is created but the URL displays a blank page. The log file says "time out".

I know why I get this problem but I don't how fix to it.

In the VH of the reverse proxy, I set :
ProxyRequests Off
ProxyPass / https://IP_server/
ProxyPassReverse / https://IP_server/
And my ServerName is : pydio.ch-nevers.fr

When a link is created, the link becomes : https://pydio.ch-nevers.fr/public/azerezrver (azerzrae is an exemple, the value is incremented randomly).

I think that problem come from the link because the reverseproxy doesn't know where or how to redirect the link to the server.

Any Ideas ?

Malcolm

**Comment by CHBMB** [comment]
Closing this, not an issue with the container.  It's a support query.  

Please use our [forum](https://discourse.linuxserver.io/) or [Discord](https://discord.gg/YWrKVTn) for support
