### ISSUE TITLE
Server not found (404), is it up and has it Pydio installed ?

### ISSUE THREAD

**Issue by Sparh4wk** [linuxserver/docker-pydio#34]
Hi,

Im not able to connect to pydio server from pc client. 
Im able to connect from android app and from browser as well.

Im getting this error msg:
![](https://i.imgur.com/zbgJvNr.png)

I tryed everything that I was able to find on pydio support forums, but no luck at all :( (I even tryed fix#28)

Instalation was ok, Im using this setup:

docker create --name=pydio --link mysql:db \
-v /etc/localtime:/etc/localtime:ro \
-v /data/config/pydio/config/:/config \
-v /data/config/pydio/data/:/data \
-e PGID=1000 -e PUID=1000  \
-p 9999:443 \
linuxserver/pydio

Im able to upload files via browser as well.. My only problem is, that I cant access it via pydio pc client.
Sorry if my question is dumb, Im causual linux user and I wanna finally ditch seafile for other self hosted software and my/owncloud is slow, so I really wanna try this one out.
If you need more info, just ask.

Thanks for all suggestions.

P.S. Is it safe to upgrade the application via Update Engine inside webadmin? or is there better way to do it.

**Comment by CHBMB** [comment]
Closing this, not an issue with the container.  It's a support query.  

Please use our [forum](https://discourse.linuxserver.io/) or [Discord](https://discord.gg/YWrKVTn) for support
