### ISSUE TITLE
since pydio:8.2.3-ls8 tag: PHP error: There was an error trying to connect to your database!

### ISSUE THREAD

**Issue by mammo0** [linuxserver/docker-pydio#39]
Hello,
since the `pydio:8.2.3-ls8` (up to `latest`) release on DockerHub I can't connect to my Pydio instance. It fails with an 500 error on Nginx. In the `error_pydio6_log` there was the following error:
```
2019/05/11 16:49:37 [error] 309#309: *1 FastCGI sent in stderr: "PHP message: Error while trying to write to logger: There was an error trying to connect to your database! Did you change any configuration for the core connection? Or maybe your database is down?
PHP message: Exception was caught but could not be logged properly: There was an error trying to connect to your database! Did you change any configuration for the core connection? Or maybe your database is down? in /config/www/pydio/plugins/conf.sql/SqlConfDriver.php on line 113
PHP message:  ===> Exception details : /config/www/pydio/plugins/conf.sql/SqlConfDriver.php on line 113 #0 /config/www/pydio/core/src/pydio/Core/PluginFramework/PluginsService.php(568): Pydio\Conf\Sql\SqlConfDriver->init(Object(Pydio\Core\Model\Context), Array)
#1 /config/www/pydio/core/src/pydio/Core/Services/ConfService.php(192): Pydio\Core\PluginFramework\PluginsService->softLoad('conf.sql', Array)
#2 /config/www/pydio/plugins/core.conf/CoreConfLoader.php(54): Pydio\Core\Services\ConfService::instanciatePluginFromGlobalParams(Array, 'Pydio\\Conf\\Core...', Object(Pydio\Core\PluginFramework\PluginsService))
#3 /config/www/pydio/core/src/pydio/Core/Services/ConfService.php(251): Pydio\Conf\Core\CoreConfLoader->getImplementation()
#4 /config/www/pydio/core/src/pydio/Core/Services/ConfService.php(116): Pydio\Core\Services\ConfService::getConfStorageImpl()
#5 /config/www/pydio/core/src/pydio/Core/Services/ConfService.php(102): Pydio\Core\Services\ConfService->startInst()
#6 /config/www/pydio/core/src/pydio/" while reading response header from upstream, client: <docker_container_ip>, server: _, request: "GET / HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "<hostname_removed>"
```

I checked my database container, but it's up and running without any problems. I can also ping the database container from within the pydio container. Other applications using the same database container do also have no problems reaching it and running queries on it.

I also tried the steps suggested in this thread: https://forum.pydio.com/t/solved-error-when-changing-php-version/452/4. But I didn't had any success. The same error persists.
The only solution I found, was reverting back to the `pydio:8.2.3-ls7` tag. If I start my container with this image (and the same settings), Pydio got no problems connecting to my database.

Host OS: debian Stretch; 4.9.0-4-amd64
I started the container with the default create syntax provided in the Readme:
```
docker create \
  --name=pydio \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Berlin \
  -p 443:443 \
  -v <my_config_volume>:/config \
  -v <my_data_volume>:/data \
  -v <bind_mount_to_external_data>:/ext \
  --restart unless-stopped \
  linuxserver/pydio
```

**Comment by thelamer** [comment]
I just did a clean install at head using our mariadb container no problems here: 
```
docker run --rm -it \
  --name=mariadb \
  -e MYSQL_ROOT_PASSWORD=rootpassword \
  -e TZ=Europe/London \
  -e MYSQL_DATABASE=pydio \
  -e MYSQL_USER=dbuser \
  -e MYSQL_PASSWORD=dbpassword \
  -p 3306:3306 \
  linuxserver/mariadb bash

docker run --rm -it \
  --name=pydio \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -p 443:443 \
  linuxserver/pydio bash
```

Went through the wizard and everything is dandy. 

This is a weird container as it installs the application to persistent folder share and not inside the container, so when you upgrade the container you are not actually upgrading the application just the core OS and files for the container. 
You need to use their "update engine" in the web interface to actually update it. 

In any case we try out best to ensure upgrades work, but we do not officially support them as it is a nightmare, and particularly with containers that install to a persistent folder it can be many versions difference. 

Use the old tag if it works and stick with it.

**Comment by mammo0** [comment]
Thanks for the reply!

Meanwhile I found out what was wrong... It was the `default` Nginx configuration file. I replaced the old one with the new version from the repo. After that I deleted the whole cache directory on the data volume and restarted the container with the latest image.
It works now again without any problems.

Sorry for your unnecessary inconvenience.
