### ISSUE TITLE
Any chance of switching to Pydio Cells?

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-pydio#41]
It seems Pydio won't get updated after this year and the dev are suggesting to switch to https://github.com/pydio/cells

Any chance you guys can create a cells docker image for all the architectures?

**Comment by hadim** [comment]
I would be interested in this too.

**Comment by aptalca** [comment]
It seems they already have an official docker image: https://pydio.com/en/docs/cells/v2/launching-docker

**Comment by thelamer** [comment]
Now live https://hub.docker.com/r/linuxserver/pydio-cells
