### ISSUE TITLE
AJXP_DATA_PATH error

### ISSUE THREAD

**Issue by latimeria68** [linuxserver/docker-pydio#43]
Hello,
trying to get Pydio working on my Orangepi pc2 via Portainer stack with:
version: "2"
services:
  pydio:
    image: linuxserver/pydio
    container_name: pydio
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Rome
    volumes:
      - /srv/dev-disk-by-label-orangepi2/config/pydio:/config
      - /srv/dev-disk-by-label-orangepi2:/data
    ports:
      - 4343:443
    restart: unless-stopped

but I always receive this error:
`Impossible write into the AJXP_DATA_PATH folder: Make sure to grant write access to this folder for your webserver!`
quite sure it'a a permission issue but why?
Thank you

**Comment by aptalca** [comment]
Most likely due to how you mounted the disk

**Comment by latimeria68** [comment]
Well I have many containers working with config on not system disk without problems, this to be safe from system disk crash and mostly used with sbc. Maybe the problem in case like this is to set the owner of the /config folder for pydio. Should it be www-data?

**Comment by aptalca** [comment]
It is set through the PUID/PGID env vars and the container does it automatically.

Many containers working fine doesn't translate into all containers should work. All images are different. Most of the apps were not designed for running in a docker container so we use a lot of different tricks to make them work.

Post your fstab and we'll take a look.
Also post a full log

**Comment by aptalca** [comment]
Wait, I just looked through the code and it seems we might not be doing a chown on the data folder.

Try this `docker exec -it pydio chown -R abc:abc /data` and restart container

**Comment by latimeria68** [comment]
Well, I completely misunderstood what the /data folder was for and that caused all the permission troubles. You pointed me to the right way thank you for prompt support.
