### ISSUE TITLE
Pydio is not compatible with PHP 7.4

### ISSUE THREAD

**Issue by wadelson** [linuxserver/docker-pydio#48]
There are multiple sources mentioning that Pydio is indeed not compatible with PHP 7.4 (and will never be as it's unsupported since Dec. 31st 2019)

https://forum.pydio.com/t/forced-to-upgrade-to-php-7-2/1966/11
https://forum.pydio.com/t/pydio-not-working-after-php-version-change/3624/2

We are seeing errors in the logs related to deprecated functions.
Users creation also doesn't seem to work.

-> We should probably leave PHP on version 7.3

**Comment by aptalca** [comment]
We'll probably push one last update with php 7.3 and deprecate this.

Thanks for the heads up.

**Comment by wadelson** [comment]
Nice, thanks for your responsiveness !

It'd be massively helpful to have one last fully working image.
